

-- ===============================
-- 1. 创建主表
-- ===============================

DROP TABLE sys_task_record;
CREATE TABLE sys_task_record (
    -- 主键ID，会自动创建一个序列并设置默认值，是 PostgreSQL 的标准做法。
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type   varchar(10)  default 'mail'::varchar,
    -- 存储任务数据，最大长度为255字符。
    data VARCHAR(255),
    -- 任务状态，不允许为空，默认值为 'PENDING'。
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    -- 错误信息，使用 TEXT 类型以存储可变长度的长文本。
    error_msg TEXT,
    -- 重试次数，默认为 0。
    -- 使用 INTEGER 而非 INT 是更明确的写法，但两者在PG中均可。
    retry_count INTEGER DEFAULT 0,
    tenant_id          varchar(20)      default '000000'::varchar,
    create_dept        int8,
    -- 记录创建时间，默认值为当前时间戳。
    -- NOW() 和 CURRENT_TIMESTAMP 在此场景下功能相同。
    create_by          int8,
    create_time        timestamp DEFAULT NOW(),
    -- 记录更新时间，默认值为当前时间戳。
    -- 注意：此字段的自动更新功能由下面的触发器实现。
    update_by          int8,
    update_time        timestamp DEFAULT NOW(),
    del_flag           char             default '0'::bpchar
);

-- public.sys_task_record definition

-- Drop table

-- DROP TABLE public.sys_task_record;

CREATE TABLE public.sys_task_record (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, -- 自增id
	task_type varchar(10) DEFAULT 'mail'::character varying NULL, -- 任务类型
	"data" varchar(255) NULL, -- 数据
	status varchar(20) DEFAULT 'PENDING'::character varying NOT NULL, -- 状态
	error_msg text NULL, -- 错误消息
	retry_count int4 DEFAULT 0 NULL, -- 重试次数
	tenant_id varchar(20) DEFAULT '000000'::character varying NULL, -- 租户
	create_dept int8 NULL, -- 创建时间
	create_by int8 NULL, -- 创建人
	create_time timestamp DEFAULT now() NULL, -- 创建时间
	update_by int8 NULL, -- 更新人
	update_time timestamp DEFAULT now() NULL, -- 更新时间
	del_flag bpchar(1) DEFAULT '0'::bpchar NULL, -- 逻辑删除标志
	CONSTRAINT sys_task_record_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE public.sys_task_record IS '系统任务状态记录机器';

-- Column comments

COMMENT ON COLUMN public.sys_task_record.id IS '自增id';
COMMENT ON COLUMN public.sys_task_record.task_type IS '任务类型';
COMMENT ON COLUMN public.sys_task_record."data" IS '数据';
COMMENT ON COLUMN public.sys_task_record.status IS '状态';
COMMENT ON COLUMN public.sys_task_record.error_msg IS '错误消息';
COMMENT ON COLUMN public.sys_task_record.retry_count IS '重试次数';
COMMENT ON COLUMN public.sys_task_record.tenant_id IS '租户';
COMMENT ON COLUMN public.sys_task_record.create_dept IS '创建时间';
COMMENT ON COLUMN public.sys_task_record.create_by IS '创建人';
COMMENT ON COLUMN public.sys_task_record.create_time IS '创建时间';
COMMENT ON COLUMN public.sys_task_record.update_by IS '更新人';
COMMENT ON COLUMN public.sys_task_record.update_time IS '更新时间';
COMMENT ON COLUMN public.sys_task_record.del_flag IS '逻辑删除标志';





目前我设计的团购平台的数据库如下，以后可能发展成电商平台，可能要考虑外卖，秒杀，吃穿玩乐旅游景点门票上的发展，
还要考虑国际化的问题，未来电商平台中，商品及订单设计方面，能够支持外卖、吃穿玩乐、旅游门票等多样化服务，对于外卖目前主要像考虑商品及订单管理方面的支持，不考虑其他，门票也是，
着重从订单，商品，上思考，可能有秒杀活动，是否能支持，关于国际化，也主要围绕商品及订单管理方面的展示
目前表格数据库大致如下，请你根据我的问题，结合表格，进行分析和以后的扩展，帮我深度思考一下：




-- ==================== 商品管理模块 ====================

-- 商品分类表（保留原结构，支持多级分类）
CREATE TABLE IF NOT EXISTS gmt_product_category (
    category_id   INT8 PRIMARY KEY,
    tenant_id     VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    parent_id     INT8          DEFAULT 0,
    category_name VARCHAR(100)  NOT NULL,
    category_code VARCHAR(100)  DEFAULT ''::VARCHAR,
    icon          VARCHAR(500)  DEFAULT ''::VARCHAR,
    sort_order    INT4          DEFAULT 0,
    status        CHAR          DEFAULT '0'::BPCHAR,
    del_flag      CHAR          DEFAULT '0'::BPCHAR,
    create_dept   INT8,
    create_by     INT8,
    create_time   TIMESTAMP,
    update_by     INT8,
    update_time   TIMESTAMP,
    remark        VARCHAR(500)  DEFAULT NULL::VARCHAR
);

COMMENT ON TABLE gmt_product_category IS '商品分类表';
COMMENT ON COLUMN gmt_product_category.category_id   IS '分类ID（主键）';
COMMENT ON COLUMN gmt_product_category.tenant_id     IS '租户编号';
COMMENT ON COLUMN gmt_product_category.parent_id     IS '父分类ID（0为一级分类）';
COMMENT ON COLUMN gmt_product_category.category_name IS '分类名称';
COMMENT ON COLUMN gmt_product_category.category_code IS '分类编码';
COMMENT ON COLUMN gmt_product_category.icon          IS '分类图标';
COMMENT ON COLUMN gmt_product_category.sort_order    IS '排序权重';
COMMENT ON COLUMN gmt_product_category.status        IS '状态（0正常 1停用）';
COMMENT ON COLUMN gmt_product_category.del_flag      IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_product_category.create_dept   IS '创建部门';
COMMENT ON COLUMN gmt_product_category.create_by     IS '创建者';
COMMENT ON COLUMN gmt_product_category.create_time   IS '创建时间';
COMMENT ON COLUMN gmt_product_category.update_by     IS '更新者';
COMMENT ON COLUMN gmt_product_category.update_time   IS '更新时间';
COMMENT ON COLUMN gmt_product_category.remark        IS '备注';

-- SPU标准产品单元表（原gmt_product升级）
CREATE TABLE IF NOT EXISTS gmt_product_spu (
    spu_id          INT8 PRIMARY KEY,
    tenant_id       VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    category_id     INT8          NOT NULL,
    product_type VARCHAR(20) DEFAULT 'physical',
    spu_name        VARCHAR(200)  NOT NULL,
    spu_desc        TEXT,
    packing_list    VARCHAR(1000),
    after_service   VARCHAR(1000),
    generic_spec    JSONB DEFAULT '{}'::JSONB,
    spu_images      VARCHAR(1000) DEFAULT ''::VARCHAR,
    brand_id        INT8          DEFAULT 0,
    status          CHAR          DEFAULT '0'::BPCHAR,
    audit_status    CHAR          DEFAULT '0'::BPCHAR,
    del_flag        CHAR          DEFAULT '0'::BPCHAR,
    create_dept     INT8,
    create_by       INT8,
    create_time     TIMESTAMP,
    update_by       INT8,
    update_time     TIMESTAMP,
    remark          VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_spu_category FOREIGN KEY (category_id) REFERENCES gmt_product_category(category_id)
);

COMMENT ON TABLE gmt_product_spu IS 'SPU标准产品单元表';
COMMENT ON COLUMN gmt_product_spu.spu_id          IS 'SPU ID（主键）';
COMMENT ON COLUMN gmt_product_spu.tenant_id       IS '租户编号';
COMMENT ON COLUMN gmt_product_spu.category_id     IS '分类ID';
COMMENT ON COLUMN gmt_product_spu.product_type     IS '分类：physical（实物）virtual（虚拟卡密）ticket（电子票券）food_delivery（外卖）service（到店服务，如按摩、美发）course（在线课程）travel（景区门票/旅游项目）seckill（秒杀商品）';
COMMENT ON COLUMN gmt_product_spu.spu_name        IS 'SPU名称';
COMMENT ON COLUMN gmt_product_spu.spu_desc        IS 'SPU描述';
COMMENT ON COLUMN gmt_product_spu.packing_list      IS '商品打包信息';
COMMENT ON COLUMN gmt_product_spu.after_service      IS '售后服务';
COMMENT ON COLUMN gmt_product_spu.generic_spec      IS '规格说明';
COMMENT ON COLUMN gmt_product_spu.spu_images      IS 'SPU图片JSON';
COMMENT ON COLUMN gmt_product_spu.brand_id        IS '品牌ID';
COMMENT ON COLUMN gmt_product_spu.status          IS '状态（0在售 1下架 2预售）';
COMMENT ON COLUMN gmt_product_spu.audit_status    IS '审核状态（0待审核 1通过 2拒绝）';
COMMENT ON COLUMN gmt_product_spu.del_flag        IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_product_spu.create_dept     IS '创建部门';
COMMENT ON COLUMN gmt_product_spu.create_by       IS '创建者';
COMMENT ON COLUMN gmt_product_spu.create_time     IS '创建时间';
COMMENT ON COLUMN gmt_product_spu.update_by       IS '更新者';
COMMENT ON COLUMN gmt_product_spu.update_time     IS '更新时间';
COMMENT ON COLUMN gmt_product_spu.remark          IS '备注';

-- SKU库存单元表（新增）采用EAV（实体-属性-值）模型与结构化字段相结合的方式，对高频属性保留结构化字段，低频属性使用EAV表  。例如，外卖SKU的规格可包含"配送时间"、"包装类型"等结构化字段，而门票SKU的规格可包含"日期"、"场次"等JSONB字段。
CREATE TABLE IF NOT EXISTS gmt_product_sku (
    sku_id         INT8 PRIMARY KEY,
    tenant_id      VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    spu_id         INT8          NOT NULL,
    sku_name       VARCHAR(200)  NOT NULL,
    sku_spec       JSONB         DEFAULT '{}'::JSONB, -- 规格JSON：{"颜色":"红色","尺寸":"XL"}
    original_price INT4 DEFAULT 0,
    group_price    INT4 DEFAULT 0,
    inventory_type VARCHAR(20) DEFAULT 'finite'
    stock_quantity INT4          DEFAULT 0,
    sold_quantity  INT4          DEFAULT 0,
    status         CHAR          DEFAULT '0'::BPCHAR,
    del_flag       CHAR          DEFAULT '0'::BPCHAR,
    create_dept    INT8,
    create_by      INT8,
    create_time    TIMESTAMP,
    update_by      INT8,
    update_time    TIMESTAMP,
    remark         VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_sku_spu FOREIGN KEY (spu_id) REFERENCES gmt_product_spu(spu_id)
);

COMMENT ON TABLE gmt_product_sku IS 'SKU库存单元表';
COMMENT ON COLUMN gmt_product_sku.sku_id         IS 'SKU ID（主键）';
COMMENT ON COLUMN gmt_product_sku.tenant_id      IS '租户编号';
COMMENT ON COLUMN gmt_product_sku.spu_id         IS 'SPU ID';
COMMENT ON COLUMN gmt_product_sku.sku_name       IS 'SKU名称';
COMMENT ON COLUMN gmt_product_sku.sku_spec       IS '规格JSON';
COMMENT ON COLUMN gmt_product_sku.original_price IS '原价（单位：分）';
COMMENT ON COLUMN gmt_product_sku.group_price    IS '团购价（单位：分）';
COMMENT ON COLUMN gmt_product_sku.inventory_type    IS 'finite: 有限库存 infinite: 无限库存（虚拟商品/票券）daily_limit: 每日限售';
COMMENT ON COLUMN gmt_product_sku.stock_quantity IS '库存数量';
COMMENT ON COLUMN gmt_product_sku.sold_quantity  IS '已售数量';
COMMENT ON COLUMN gmt_product_sku.status         IS '状态（0正常 1停用）';
COMMENT ON COLUMN gmt_product_sku.del_flag       IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_product_sku.create_dept    IS '创建部门';
COMMENT ON COLUMN gmt_product_sku.create_by      IS '创建者';
COMMENT ON COLUMN gmt_product_sku.create_time    IS '创建时间';
COMMENT ON COLUMN gmt_product_sku.update_by      IS '更新者';
COMMENT ON COLUMN gmt_product_sku.update_time    IS '更新时间';
COMMENT ON COLUMN gmt_product_sku.remark         IS '备注';


-- 商品SKU关联表（对sku_spec 规格的结构化扩展）
CREATE TABLE IF NOT EXISTS gmt_product_sku_attributes (
    sku_attr_id     INT8 PRIMARY KEY,
    sku_id INT8 NOT NULL,
    attr_key    VARCHAR(50) NOT NULL,
    attr_value  VARCHAR(500) NOT NULL,
    attr_type   VARCHAR(50) DEFAULT 'string'::VARCHAR,
    CONSTRAINT fk_sku_id FOREIGN KEY (sku_id) REFERENCES gmt_product_sku(sku_id)
);
COMMENT ON TABLE gmt_product_sku_attributes IS '商品SKU属性表';
COMMENT ON COLUMN gmt_product_sku_attributes.sku_attr_id IS '属性ID (主键)';
COMMENT ON COLUMN gmt_product_sku_attributes.sku_id IS '商品ID';
COMMENT ON COLUMN gmt_product_sku_attributes.attr_key IS '属性键';-- color,size
COMMENT ON COLUMN gmt_product_sku_attributes.attr_value IS '属性值';
COMMENT ON COLUMN gmt_product_sku_attributes.attr_type IS '属性类型';

CREATE TABLE gmt_attr_i18n (
    i18n_id      BIGSERIAL PRIMARY KEY,
    attr_key     VARCHAR(50) NOT NULL,  -- 与 attributes 表对应
    attr_value   VARCHAR(200) NOT NULL, -- value code:color,size
    lang         VARCHAR(10) NOT NULL,  -- zh / en / ja
    display_text VARCHAR(200) NOT NULL, -- 用于前端显示的翻译
    UNIQUE(attr_key, attr_value, lang)
);



-- 团购活动表（优化：支持多商品）
CREATE TABLE IF NOT EXISTS gmt_activity (
    activity_id       INT8 PRIMARY KEY,
    tenant_id         VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    activity_name     VARCHAR(200)  NOT NULL,
    activity_type     VARCHAR(50)   DEFAULT 'group'::VARCHAR,
    cover_image       VARCHAR(500)  DEFAULT ''::VARCHAR,
    share_title       VARCHAR(200)  DEFAULT ''::VARCHAR,
    share_description VARCHAR(500)  DEFAULT ''::VARCHAR,
    start_time        TIMESTAMP,
    end_time          TIMESTAMP,
    success_count     INT4          DEFAULT 0,
    status            CHAR          DEFAULT '0'::BPCHAR,
    audit_status      CHAR          DEFAULT '0'::BPCHAR,
    del_flag          CHAR          DEFAULT '0'::BPCHAR,
    create_dept       INT8,
    create_by         INT8,
    create_time       TIMESTAMP,
    update_by         INT8,
    update_time       TIMESTAMP,
    remark            VARCHAR(500)  DEFAULT NULL::VARCHAR
);

COMMENT ON TABLE gmt_activity IS '团购活动表';
COMMENT ON COLUMN gmt_activity.activity_id       IS '活动ID（主键）';
COMMENT ON COLUMN gmt_activity.tenant_id         IS '租户编号';
COMMENT ON COLUMN gmt_activity.activity_name     IS '活动名称';
COMMENT ON COLUMN gmt_activity.activity_type     IS '活动类型：group（拼团）seckill（秒杀）discount（折扣）full_reduction（满减）coupon（优惠券活动）flash_sale（限时抢购）';
COMMENT ON COLUMN gmt_activity.cover_image       IS '活动封面图';
COMMENT ON COLUMN gmt_activity.share_title       IS '分享标题';
COMMENT ON COLUMN gmt_activity.share_description IS '分享描述';
COMMENT ON COLUMN gmt_activity.start_time        IS '开始时间';
COMMENT ON COLUMN gmt_activity.end_time          IS '结束时间';
COMMENT ON COLUMN gmt_activity.success_count     IS '成功团购次数';
COMMENT ON COLUMN gmt_activity.status            IS '活动状态（0未开始 1进行中 2已结束）';
COMMENT ON COLUMN gmt_activity.audit_status      IS '审核状态（0待审核 1通过 2拒绝）';
COMMENT ON COLUMN gmt_activity.del_flag          IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_activity.create_dept       IS '创建部门';
COMMENT ON COLUMN gmt_activity.create_by         IS '创建者';
COMMENT ON COLUMN gmt_activity.create_time       IS '创建时间';
COMMENT ON COLUMN gmt_activity.update_by         IS '更新者';
COMMENT ON COLUMN gmt_activity.update_time       IS '更新时间';
COMMENT ON COLUMN gmt_activity.remark            IS '备注';

-- 如果未来需要增加新的活动类型，如“满减活动”或“折扣券活动”，这些活动可能不需要“成团人数”或“活动库存”等字段，但这些字段依然会存在于表中
-- 活动商品关联表（新增：实现多对多关系+快照）
CREATE TABLE IF NOT EXISTS gmt_activity_attributes (
    attr_id     INT8 PRIMARY KEY,
    activity_id INT8 NOT NULL,
    attr_key    VARCHAR(100) NOT NULL,
    attr_value  VARCHAR(500) NOT NULL,
    attr_type   VARCHAR(50) DEFAULT 'string'::VARCHAR,
    CONSTRAINT fk_attr_activity FOREIGN KEY (activity_id) REFERENCES gmt_activity(activity_id)
);
COMMENT ON TABLE gmt_activity_attributes IS '活动属性表';
COMMENT ON COLUMN gmt_activity_attributes.attr_id IS '属性ID (主键)';
COMMENT ON COLUMN gmt_activity_attributes.activity_id IS '活动ID';
COMMENT ON COLUMN gmt_activity_attributes.attr_key IS '属性键';
COMMENT ON COLUMN gmt_activity_attributes.attr_value IS '属性值';
COMMENT ON COLUMN gmt_activity_attributes.attr_type IS '属性类型';

-- 活动商品关联表（新增：实现多对多关系+快照）
CREATE TABLE IF NOT EXISTS gmt_activity_product (
    activity_product_id INT8 PRIMARY KEY,
    tenant_id           VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    activity_id         INT8          NOT NULL,
    spu_id              INT8          NOT NULL,
    sku_id              INT8          NOT NULL,
    activity_title      VARCHAR(200)  NOT NULL,
    group_price         INT4 DEFAULT 0,
    stock_quantity      INT4          DEFAULT 0,
    min_group_size      INT4          DEFAULT 2,
    max_group_size      INT4          DEFAULT 999,
    limit_per_user      INT4          DEFAULT 999,
    status              CHAR          DEFAULT '0'::BPCHAR,
    audit_status        CHAR          DEFAULT '0'::BPCHAR,
    del_flag            CHAR          DEFAULT '0'::BPCHAR,
    create_dept         INT8,
    create_by           INT8,
    create_time         TIMESTAMP,
    update_by           INT8,
    update_time         TIMESTAMP,
    remark              VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_act_product_activity  FOREIGN KEY (activity_id) REFERENCES gmt_activity(activity_id),
    CONSTRAINT fk_act_product_spu       FOREIGN KEY (spu_id)      REFERENCES gmt_product_spu(spu_id),
    CONSTRAINT fk_act_product_sku       FOREIGN KEY (sku_id)      REFERENCES gmt_product_sku(sku_id)
);

COMMENT ON TABLE gmt_activity_product IS '活动商品关联表';
COMMENT ON COLUMN gmt_activity_product.activity_product_id IS '关联ID（主键）';
COMMENT ON COLUMN gmt_activity_product.tenant_id           IS '租户编号';
COMMENT ON COLUMN gmt_activity_product.activity_id         IS '活动ID';
COMMENT ON COLUMN gmt_activity_product.spu_id              IS 'SPU ID';
COMMENT ON COLUMN gmt_activity_product.sku_id              IS 'SKU ID';
COMMENT ON COLUMN gmt_activity_product.activity_title      IS '活动商品标题（快照）';
COMMENT ON COLUMN gmt_activity_product.group_price         IS '团购价格（快照）';
COMMENT ON COLUMN gmt_activity_product.stock_quantity      IS '活动库存';
COMMENT ON COLUMN gmt_activity_product.min_group_size      IS '最小成团人数';
COMMENT ON COLUMN gmt_activity_product.max_group_size      IS '最大成团人数';
COMMENT ON COLUMN gmt_activity_product.limit_per_user      IS '每人限购数量';
COMMENT ON COLUMN gmt_activity_product.status              IS '状态（0正常 1停用）';
COMMENT ON COLUMN gmt_activity_product.audit_status        IS '审核状态';
COMMENT ON COLUMN gmt_activity_product.del_flag            IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_activity_product.create_dept         IS '创建部门';
COMMENT ON COLUMN gmt_activity_product.create_by           IS '创建者';
COMMENT ON COLUMN gmt_activity_product.create_time         IS '创建时间';
COMMENT ON COLUMN gmt_activity_product.update_by           IS '更新者';
COMMENT ON COLUMN gmt_activity_product.update_time         IS '更新时间';
COMMENT ON COLUMN gmt_activity_product.remark              IS '备注';

-- ==================== 拼团模块 ====================

-- 团购参团记录表（优化：保留作为团单头）
CREATE TABLE IF NOT EXISTS gmt_group_record (
    record_id      INT8 PRIMARY KEY,
    tenant_id      VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    activity_product_id INT8     NOT NULL,
    leader_id      INT8          NOT NULL,
    current_count  INT4          DEFAULT 1,
    target_count   INT4          NOT NULL,
    group_status   CHAR          DEFAULT '0'::BPCHAR,
    expire_time    TIMESTAMP,
    version INT4 DEFAULT 0,
    del_flag       CHAR          DEFAULT '0'::BPCHAR,
    create_dept    INT8,
    create_by      INT8,
    create_time    TIMESTAMP,
    update_by      INT8,
    update_time    TIMESTAMP,
    remark         VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_group_activity_product FOREIGN KEY (activity_product_id) REFERENCES gmt_activity_product(activity_product_id),
    CONSTRAINT fk_group_leader          FOREIGN KEY (leader_id)           REFERENCES sys_user(user_id)
);
UPDATE gmt_group_record
SET current_count = current_count + 1, version = version + 1
WHERE record_id = ? AND version = ?

COMMENT ON TABLE gmt_group_record IS '团购参团记录表';
COMMENT ON COLUMN gmt_group_record.record_id          IS '参团记录ID（主键）';
COMMENT ON COLUMN gmt_group_record.tenant_id          IS '租户编号';
COMMENT ON COLUMN gmt_group_record.activity_product_id IS '活动商品ID';
COMMENT ON COLUMN gmt_group_record.leader_id          IS '团长用户ID';
COMMENT ON COLUMN gmt_group_record.current_count      IS '当前参团人数';
COMMENT ON COLUMN gmt_group_record.target_count       IS '目标成团人数';
COMMENT ON COLUMN gmt_group_record.group_status       IS '成团状态（0拼团中 1成团成功 2成团失败）';
COMMENT ON COLUMN gmt_group_record.expire_time        IS '成团截止时间';
COMMENT ON COLUMN gmt_group_record.version        IS '（乐观锁）避免拼团人数增加时出现并发问题';
COMMENT ON COLUMN gmt_group_record.del_flag           IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_group_record.create_dept        IS '创建部门';
COMMENT ON COLUMN gmt_group_record.create_by          IS '创建者';
COMMENT ON COLUMN gmt_group_record.create_time        IS '创建时间';
COMMENT ON COLUMN gmt_group_record.update_by          IS '更新者';
COMMENT ON COLUMN gmt_group_record.update_time        IS '更新时间';
COMMENT ON COLUMN gmt_group_record.remark             IS '备注';

-- 拼团团员表（新增：记录参与用户）
CREATE TABLE IF NOT EXISTS gmt_group_member (
    member_id   INT8 PRIMARY KEY,
    tenant_id   VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    record_id   INT8          NOT NULL,
    user_id     INT8          NOT NULL,
    order_id    INT8          NOT NULL,
    join_time   TIMESTAMP     DEFAULT NOW(),
    status      CHAR          DEFAULT '0'::BPCHAR,
    del_flag    CHAR          DEFAULT '0'::BPCHAR,
    create_dept INT8,
    create_by   INT8,
    create_time TIMESTAMP,
    update_by   INT8,
    update_time TIMESTAMP,
    remark      VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_member_record FOREIGN KEY (record_id) REFERENCES gmt_group_record(record_id),
    CONSTRAINT fk_member_user   FOREIGN KEY (user_id)   REFERENCES sys_user(user_id),
    CONSTRAINT fk_member_order  FOREIGN KEY (order_id)  REFERENCES gmt_order(order_id)
);

COMMENT ON TABLE gmt_group_member IS '拼团团员表';
COMMENT ON COLUMN gmt_group_member.member_id   IS '团员ID（主键）';
COMMENT ON COLUMN gmt_group_member.tenant_id   IS '租户编号';
COMMENT ON COLUMN gmt_group_member.record_id   IS '参团记录ID';
COMMENT ON COLUMN gmt_group_member.user_id     IS '用户ID';
COMMENT ON COLUMN gmt_group_member.order_id    IS '订单ID';
COMMENT ON COLUMN gmt_group_member.join_time   IS '加入时间';
COMMENT ON COLUMN gmt_group_member.status      IS '状态（0已支付 1退款中 2已退款）';
COMMENT ON COLUMN gmt_group_member.del_flag    IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_group_member.create_dept IS '创建部门';
COMMENT ON COLUMN gmt_group_member.create_by   IS '创建者';
COMMENT ON COLUMN gmt_group_member.create_time IS '创建时间';
COMMENT ON COLUMN gmt_group_member.update_by   IS '更新者';
COMMENT ON COLUMN gmt_group_member.update_time IS '更新时间';
COMMENT ON COLUMN gmt_group_member.remark      IS '备注';

-- ==================== 订单与物流模块 ====================

-- 团购订单表（优化：补充完整外键）
CREATE TABLE IF NOT EXISTS gmt_order (
    order_id           INT8 PRIMARY KEY,
    tenant_id          VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    order_sn           VARCHAR(64)   NOT NULL UNIQUE,
    user_id            INT8          NOT NULL,
    activity_id        INT8          NOT NULL,
    activity_product_id INT8         NOT NULL,
    group_record_id    INT8,
    parent_order_id    INT8,
    product_type VARCHAR(20) DEFAULT 'physical', -- 'normal'普通 | 'food_delivery'外卖 | 'ticket'门票 | 'service'服务
    extend_json JSONB,   -- (用于存储不同业务类型的特殊字段)
    fulfillment_mode VARCHAR(20) DEFAULT 'delivery'; -- 'delivery'物流 | 'code'核销码 | 'self_pick'自提
    order_status       CHAR          DEFAULT '0'::BPCHAR,
    pay_status         CHAR          DEFAULT '0'::BPCHAR,
    pay_amount         INT4 DEFAULT 0,
    pay_time           TIMESTAMP,
    pay_way            VARCHAR(20)   DEFAULT ''::VARCHAR,
    receiver_name      VARCHAR(50)   NOT NULL,
    receiver_phone     VARCHAR(20)   NOT NULL,
    receiver_province  VARCHAR(50)   DEFAULT ''::VARCHAR,
    receiver_city      VARCHAR(50)   DEFAULT ''::VARCHAR,
    receiver_district  VARCHAR(50)   DEFAULT ''::VARCHAR,
    receiver_address   VARCHAR(200)  NOT NULL,
    logistics_no       VARCHAR(100)  DEFAULT ''::VARCHAR,
    logistics_company  VARCHAR(100)  DEFAULT ''::VARCHAR,
    buyer_message      VARCHAR(500)  DEFAULT ''::VARCHAR,
    auto_confirm_days  INT4          DEFAULT 7,
    confirm_time       TIMESTAMP,
    refund_status      CHAR          DEFAULT '0'::BPCHAR,
    refund_amount      INT4 DEFAULT 0,
    source             VARCHAR(50)   DEFAULT '小程序'::VARCHAR,
    del_flag           CHAR          DEFAULT '0'::BPCHAR,
    create_dept        INT8,
    create_by          INT8,
    create_time        TIMESTAMP,
    update_by          INT8,
    update_time        TIMESTAMP,
    remark             VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_order_user            FOREIGN KEY (user_id)            REFERENCES sys_user(user_id),
    CONSTRAINT fk_order_activity        FOREIGN KEY (activity_id)        REFERENCES gmt_activity(activity_id),
    CONSTRAINT fk_order_activity_product FOREIGN KEY (activity_product_id) REFERENCES gmt_activity_product(activity_product_id),
    CONSTRAINT fk_order_group_record    FOREIGN KEY (group_record_id)    REFERENCES gmt_group_record(record_id),
    CONSTRAINT fk_order_parent          FOREIGN KEY (parent_order_id)    REFERENCES gmt_order(order_id)
);

COMMENT ON TABLE gmt_order IS '订单表';
COMMENT ON COLUMN gmt_order.order_id              IS '订单ID（主键）';
COMMENT ON COLUMN gmt_order.tenant_id             IS '租户编号';
COMMENT ON COLUMN gmt_order.order_sn              IS '订单号（唯一）';
COMMENT ON COLUMN gmt_order.user_id               IS '用户ID（外键）';
COMMENT ON COLUMN gmt_order.group_record_id       IS '参团记录ID（外键）';
COMMENT ON COLUMN gmt_order.parent_order_id       IS '父订单ID（组合订单）按照发货地址来进行拆解';
COMMENT ON COLUMN gmt_order.product_type     IS '分类：physical（实物）virtual（虚拟卡密）ticket（电子票券）food_delivery（外卖）service（到店服务，如按摩、美发）course（在线课程）travel（景区门票/旅游项目）seckill（秒杀商品）';
COMMENT ON COLUMN gmt_order.extend_json     IS '用于存储不同业务类型的特殊字段：外卖：配送地址、时间，门票：二维码、有效期，服务：预约时间，秒杀：秒杀订单标记  通用订单表结构不会被业务类型破坏';
COMMENT ON COLUMN gmt_order.order_status          IS '订单状态（0待支付 1待发货 2已发货 3已完成 4已取消）';
COMMENT ON COLUMN gmt_order.pay_status            IS '支付状态（0未支付 1已支付 2退款中 3已退款）';
COMMENT ON COLUMN gmt_order.pay_amount            IS '支付金额 单位fen';
COMMENT ON COLUMN gmt_order.pay_time              IS '支付时间';
COMMENT ON COLUMN gmt_order.pay_way               IS '支付方式';
COMMENT ON COLUMN gmt_order.receiver_name         IS '收货人姓名';
COMMENT ON COLUMN gmt_order.receiver_phone        IS '收货人电话';
COMMENT ON COLUMN gmt_order.receiver_province     IS '省份';
COMMENT ON COLUMN gmt_order.receiver_city         IS '城市';
COMMENT ON COLUMN gmt_order.receiver_district     IS '区县';
COMMENT ON COLUMN gmt_order.receiver_address      IS '详细地址';
COMMENT ON COLUMN gmt_order.logistics_no          IS '物流单号';
COMMENT ON COLUMN gmt_order.logistics_company     IS '物流公司';
COMMENT ON COLUMN gmt_order.buyer_message         IS '买家留言';
COMMENT ON COLUMN gmt_order.auto_confirm_days     IS '自动确认天数';
COMMENT ON COLUMN gmt_order.confirm_time          IS '确认收货时间';
COMMENT ON COLUMN gmt_order.refund_status         IS '退款状态（0无退款 1部分退款 2全额退款）';
COMMENT ON COLUMN gmt_order.refund_amount         IS '退款金额';
COMMENT ON COLUMN gmt_order.source                IS '订单来源（小程序/H5/APP）';
COMMENT ON COLUMN gmt_order.del_flag              IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_order.create_dept           IS '创建部门';
COMMENT ON COLUMN gmt_order.create_by             IS '创建者';
COMMENT ON COLUMN gmt_order.create_time           IS '创建时间';
COMMENT ON COLUMN gmt_order.update_by             IS '更新者';
COMMENT ON COLUMN gmt_order.update_time           IS '更新时间';
COMMENT ON COLUMN gmt_order.remark                IS '备注';


CREATE TABLE IF NOT EXISTS gmt_order_item (
    item_id             INT8 PRIMARY KEY,
    order_id            INT8 NOT NULL,
    activity_product_id INT8 NOT NULL,
    spu_id              INT8 NOT NULL,
    sku_id              INT8 NOT NULL,
    sku_name            VARCHAR(200) NOT NULL,
    sku_image           VARCHAR(500),
    price               INT4 DEFAULT 0,
    quantity            INT4 DEFAULT 1,
    total_amount        INT4 DEFAULT 0,
    refund_status       CHAR DEFAULT '0'::BPCHAR,
    refund_amount       INT4 DEFAULT 0,
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES gmt_order(order_id),
    CONSTRAINT fk_item_activity_product FOREIGN KEY (activity_product_id) REFERENCES gmt_activity_product(activity_product_id)
);
COMMENT ON TABLE gmt_order_item IS '订单明细表';
COMMENT ON COLUMN gmt_order_item.item_id IS '明细ID (主键)';
COMMENT ON COLUMN gmt_order_item.order_id IS '订单ID';
COMMENT ON COLUMN gmt_order_item.activity_product_id IS '活动商品ID';
COMMENT ON COLUMN gmt_order_item.spu_id IS 'SPU ID (冗余)';
COMMENT ON COLUMN gmt_order_item.sku_id IS 'SKU ID (冗余)';
COMMENT ON COLUMN gmt_order_item.sku_name IS '商品名称 (快照)';
COMMENT ON COLUMN gmt_order_item.sku_image IS '商品图片 (快照)';
COMMENT ON COLUMN gmt_order_item.price IS '单价';
COMMENT ON COLUMN gmt_order_item.quantity IS '数量';
COMMENT ON COLUMN gmt_order_item.total_amount IS '小计';
COMMENT ON COLUMN gmt_order_item.refund_status IS '退款状态';
COMMENT ON COLUMN gmt_order_item.refund_amount IS '退款金额';



-- 新建国际地址表
CREATE TABLE international_addresses(
    address_id INT8 PRIMARY KEY,
    country_code CHAR(2) NOT NULL, -- ISO 3166-1 alpha-2
    administrative_area VARCHAR(50), -- 省/州
    locality VARCHAR(50), -- 城市
    dependent_locality VARCHAR(50), -- 区县
    street_type VARCHAR(50), -- 街道类型
    street_number VARCHAR(50), -- 门牌号
    postal_code VARCHAR(20), -- 邮编
    formatted_address TEXT, -- 格式化地址
    lang VARCHAR(10) DEFAULT 'zh' -- 默认语言
);

-- 新建地址翻译表
CREATE TABLE address_i18n(
    address_id INT8 NOT NULL,
    lang VARCHAR(10) NOT NULL,
    translated_value TEXT NOT NULL,
    PRIMARY KEY (address_id, lang),
    FOREIGN KEY (address_id) REFERENCES international_addresses(address_id)
);

-- 修改订单表关联地址
ALTER TABLE gmt_order
ADD COLUMN address_id INT8,
ADD COLUMN delivery_address_id INT8,
ADD COLUMN billing_address_id INT8,
ADD COLUMN country_code CHAR(2),
ADD COLUMN region VARCHAR(50),
ADD COLUMN city VARCHAR(50),
ADD COLUMN district VARCHAR(50),
ADD COLUMN zip_code VARCHAR(20);

ALTER TABLE gmt_order
ADD CONSTRAINT fk_order_address FOREIGN KEY (address_id) REFERENCES international_addresses(address_id);


-- 门票/服务专用表
CREATE TABLE gmt_order_ticket (
  ticket_id INT8 PRIMARY KEY,
  order_id INT8 NOT NULL,
  code_no VARCHAR(50) NOT NULL,  -- 门票券码
  qr_code BYTEA,                 -- 二维码二进制
  valid_start TIMESTAMP,
  valid_end TIMESTAMP,
  verify_status CHAR DEFAULT '0',  -- 0未核销 1已核销
  CONSTRAINT fk_ticket_order FOREIGN KEY (order_id) REFERENCES gmt_order(order_id)
);

-- 外卖配送专用表
CREATE TABLE gmt_order_food_delivery (
  delivery_id INT8 PRIMARY KEY,
  order_id INT8 NOT NULL,
  rider_name VARCHAR(50),
  rider_phone VARCHAR(20),
  delivery_distance INT4,        -- 骑手距离门店多少米
  delivery_status VARCHAR(20) DEFAULT 'pending', -- 'pending'等待中 | 'in_transit'配送中
  CONSTRAINT fk_food_order FOREIGN KEY (order_id) REFERENCES gmt_order(order_id)
);
-- 外卖商品扩展表
CREATE TABLE gmt_product_delivery(
    spu_id INT8 PRIMARY KEY,
    deliveryRadius INT4 DEFAULT 5000, -- 配送半径（米）
    minDeliveryTime INT4, -- 最短配送时间（分钟）
    maxDeliveryTime INT4, -- 最长配送时间（分钟）
    deliveryOptions JSONB DEFAULT '{"standard": true, "express": false}', -- 配送选项
    FOREIGN KEY (spu_id) REFERENCES gmt_product_spu(spu_id)
);

-- 门票商品扩展表
CREATE TABLE gmt_product_ticket(
    spu_id INT8 PRIMARY KEY,
    validityPeriod JSONB DEFAULT '{"start": null, "end": null}', -- 有效期
    verificationRules JSONB DEFAULT '{"location": null, "codeType": "qr"}', -- 核销规则
    admissionOptions JSONB DEFAULT '{"entryPoint": null, "groupSize": 1}', -- 入场选项
    FOREIGN KEY (spu_id) REFERENCES gmt_product_spu(spu_id)
);

-- 秒杀商品扩展表
CREATE TABLE gmt_product_seckill(
    spu_id INT8 PRIMARY KEY,
    stockSnapshot INT4 NOT NULL, -- 库存快照
    seckillPeriod JSONB DEFAULT '{"start": null, "end": null}', -- 秒杀时间段
    priceStrategy JSONB DEFAULT '{"original": 0, "seckill": 0}', -- 价格策略
    FOREIGN KEY (spu_id) REFERENCES gmt_product_spu(spu_id)
);


CREATE TABLE gmt_seckill_stock_lock (
  lock_id INT8 PRIMARY KEY,
  sku_id INT8 NOT NULL,
  activity_product_id INT8 NOT NULL,
  quantity INT4 NOT NULL,
  user_id INT8 NOT NULL,
  expire_time TIMESTAMP NOT NULL,  -- 锁定5秒后过期
  status CHAR DEFAULT 'locked',   -- 'locked'锁定中 | 'released'释放
  CONSTRAINT fk_lock_sku FOREIGN KEY (sku_id) REFERENCES gmt_product_sku(sku_id)
);

-- 物流跟踪记录表（新增：独立物流轨迹）
CREATE TABLE IF NOT EXISTS gmt_logistics_history (
    history_id     INT8 PRIMARY KEY,
    tenant_id      VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    order_id       INT8          NOT NULL,
    node_time      TIMESTAMP     NOT NULL,
    node_status    VARCHAR(50)   NOT NULL,
    node_location  JSONB         DEFAULT '{}'::JSONB, -- {"province":"广东","city":"深圳","address":"南山营业部"}
    operator       VARCHAR(100)  DEFAULT ''::VARCHAR,
    remark         VARCHAR(500)  DEFAULT NULL::VARCHAR,
    del_flag       CHAR          DEFAULT '0'::BPCHAR,
    create_dept    INT8,
    create_by      INT8,
    create_time    TIMESTAMP,
    update_by      INT8,
    update_time    TIMESTAMP,
    CONSTRAINT fk_logistics_order FOREIGN KEY (order_id) REFERENCES gmt_order(order_id)
);

COMMENT ON TABLE gmt_logistics_history IS '物流跟踪记录表';
COMMENT ON COLUMN gmt_logistics_history.history_id    IS '跟踪ID（主键）';
COMMENT ON COLUMN gmt_logistics_history.tenant_id     IS '租户编号';
COMMENT ON COLUMN gmt_logistics_history.order_id      IS '订单ID（外键）';
COMMENT ON COLUMN gmt_logistics_history.node_time     IS '节点时间';
COMMENT ON COLUMN gmt_logistics_history.node_status   IS '节点状态（已揽收/运输中/派送中/已签收）';
COMMENT ON COLUMN gmt_logistics_history.node_location IS '节点位置JSON';
COMMENT ON COLUMN gmt_logistics_history.operator      IS '操作人';
COMMENT ON COLUMN gmt_logistics_history.remark        IS '备注';
COMMENT ON COLUMN gmt_logistics_history.del_flag      IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_logistics_history.create_dept   IS '创建部门';
COMMENT ON COLUMN gmt_logistics_history.create_by     IS '创建者';
COMMENT ON COLUMN gmt_logistics_history.create_time   IS '创建时间';
COMMENT ON COLUMN gmt_logistics_history.update_by     IS '更新者';
COMMENT ON COLUMN gmt_logistics_history.update_time   IS '更新时间';

-- ==================== 团长管理模块 ====================

-- 团长申请表（保留原结构，补充外键）
CREATE TABLE IF NOT EXISTS gmt_leader_apply (
    apply_id        INT8 PRIMARY KEY,
    tenant_id       VARCHAR(20)   DEFAULT '000000'::VARCHAR,
    user_id         INT8          NOT NULL,
    apply_status    CHAR          DEFAULT '0'::BPCHAR,
    commission_rate NUMERIC(5,2)  DEFAULT 0.00,
    apply_reason    VARCHAR(500)  DEFAULT ''::VARCHAR,
    audit_remark    VARCHAR(500)  DEFAULT ''::VARCHAR,
    del_flag        CHAR          DEFAULT '0'::BPCHAR,
    create_dept     INT8,
    create_by       INT8,
    create_time     TIMESTAMP,
    update_by       INT8,
    update_time     TIMESTAMP,
    remark          VARCHAR(500)  DEFAULT NULL::VARCHAR,
    CONSTRAINT fk_apply_user FOREIGN KEY (user_id) REFERENCES sys_user(user_id)
);

COMMENT ON TABLE gmt_leader_apply IS '团长申请表';
COMMENT ON COLUMN gmt_leader_apply.apply_id        IS '申请ID（主键）';
COMMENT ON COLUMN gmt_leader_apply.tenant_id       IS '租户编号';
COMMENT ON COLUMN gmt_leader_apply.user_id         IS '用户ID（外键）';
COMMENT ON COLUMN gmt_leader_apply.apply_status    IS '申请状态（0待审核 1已通过 2已拒绝）';
COMMENT ON COLUMN gmt_leader_apply.commission_rate IS '佣金比例（%）';
COMMENT ON COLUMN gmt_leader_apply.apply_reason    IS '申请理由';
COMMENT ON COLUMN gmt_leader_apply.audit_remark    IS '审核备注';
COMMENT ON COLUMN gmt_leader_apply.del_flag        IS '删除标志（0存在 1删除）';
COMMENT ON COLUMN gmt_leader_apply.create_dept     IS '创建部门';
COMMENT ON COLUMN gmt_leader_apply.create_by       IS '创建者';
COMMENT ON COLUMN gmt_leader_apply.create_time     IS '创建时间';
COMMENT ON COLUMN gmt_leader_apply.update_by       IS '更新者';
COMMENT ON COLUMN gmt_leader_apply.update_time     IS '更新时间';
COMMENT ON COLUMN gmt_leader_apply.remark          IS '备注';


-- 创建多级分销关系表
CREATE TABLE gmt_distribution_relation (
    relation_id INT8 PRIMARY KEY,
    user_id INT8 NOT NULL,
    parent_id INT8 NOT NULL,
    level INT4 NOT NULL, -- 分销层级（1级、2级等）
    commission_rate NUMERIC(5,2) DEFAULT 0.00,
    FOREIGN KEY (user_id) REFERENCES sys_user(user_id),
    FOREIGN KEY (parent_id) REFERENCES sys_user(user_id)
);

-- 创建分销关系索引
CREATE INDEX idx_distribution_relation ON gmt_distribution_relation (user_id, parent_id);



CREATE TABLE gmt_store (
    store_id INT8 PRIMARY KEY,
    tenant_id VARCHAR(20) DEFAULT '000000',
    store_name VARCHAR(100) NOT NULL,
    address VARCHAR(200) NOT NULL,
    business_hours VARCHAR(50) DEFAULT '09:00-22:00', -- 营业时间
    delivery_radius INT4 DEFAULT 5000, -- 配送半径（米）
    status CHAR DEFAULT 'open', -- 'open'营业中 | 'close'打烊
    lang VARCHAR(10) DEFAULT 'zh', -- 默认语言
    del_flag CHAR DEFAULT '0',
    create_dept INT8,
    create_by INT8,
    create_time TIMESTAMP,
    update_by INT8,
    update_time TIMESTAMP,
    remark VARCHAR(500) DEFAULT NULL
);

CREATE TABLE gmt_store_product (
    store_id INT8 NOT NULL,
    sku_id INT8 NOT NULL,
    price INT4 NOT NULL, -- 门店价
    stock INT4 NOT NULL,
    PRIMARY KEY (store_id, sku_id),
    FOREIGN KEY (store_id) REFERENCES gmt_store(store_id),
    FOREIGN KEY (sku_id) REFERENCES gmt_product Sku(sku_id)
);

CREATE TABLE gmtDelivery_address (
    address_id INT8 PRIMARY KEY,
    tenant_id VARCHAR(20) DEFAULT '000000',
    user_id INT8 NOT NULL,
    address VARCHAR(200) NOT NULL,
    province VARCHAR(50) DEFAULT '',
    city VARCHAR(50) DEFAULT '',
    district VARCHAR(50) DEFAULT '',
    latitude VARCHAR(20) DEFAULT '', -- 纬度
    longitude VARCHAR(20) DEFAULT '', -- 经度
    tag VARCHAR(50) DEFAULT '', -- 地址标签（如家、公司）
    del_flag CHAR DEFAULT '0',
    create_dept INT8,
    create_by INT8,
    create_time TIMESTAMP,
    update_by INT8,
    update_time TIMESTAMP,
    remark VARCHAR(500) DEFAULT NULL
);

CREATE TABLE gmt_order_delivery (
    order_id INT8 PRIMARY KEY,
    address_id INT8 NOT NULL,
    store_id INT8 NOT NULL,
    rider_id INT8, -- 骑手ID
    rider_name VARCHAR(50), -- 骑手姓名
    rider_phone VARCHAR(20), -- 骑手电话
    delivery_status VARCHAR(20) DEFAULT 'pending', -- 'pending'等待中 | 'in_transit'配送中 | 'delivered'已送达
    expected交付时间 TIMESTAMP,
    actual交付时间 TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES gmt_order(order_id),
    FOREIGN KEY (address_id) REFERENCES gmtDelivery_address(address_id),
    FOREIGN KEY (store_id) REFERENCES gmt_store(store_id)
);

CREATE TABLE gmt_ticket (
    ticket_id INT8 PRIMARY KEY,
    order_id INT8 NOT NULL,
    code_no VARCHAR(50) NOT NULL,  -- 券码
    qr_code BYTEA,                 -- 二维码二进制
    valid_start TIMESTAMP,
    valid_end TIMESTAMP,
    verify_status CHAR DEFAULT '0',  -- 0未核销 1已核销
    verify_time TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES gmt_order(order_id)
);

-- 创建门票国际化翻译表
CREATE TABLE gmt_ticket_i18n (
    ticket_id INT8 NOT NULL,
    lang VARCHAR(10) NOT NULL,
    description VARCHAR(500) NOT NULL,
    PRIMARY KEY (ticket_id, lang),
    FOREIGN KEY (ticket_id) REFERENCES gmtTicket(ticket_id)
);

CREATE TABLE gmt_verify (
    verify_id INT8 PRIMARY KEY,
    ticket_id INT8 NOT NULL,
    verify_time TIMESTAMP,
    verify_location VARCHAR(200),  -- 核销地点
    operator VARCHAR(100),         -- 操作人
    FOREIGN KEY (ticket_id) REFERENCES gmtTicket(ticket_id)
);


-- 通用属性表（EAV）
CREATE TABLE gmt_attributes (
  attr_id      BIGSERIAL PRIMARY KEY,
  tenant_id    VARCHAR(20) DEFAULT '000000'::varchar,
  resource_type VARCHAR(50) NOT NULL,   -- e.g. 'sku','spu','activity'
  resource_id  BIGINT NOT NULL,         -- 指向对应表的 id
  attr_key     VARCHAR(100) NOT NULL,   -- 标准化 key，例如 'color','size'
  attr_value   VARCHAR(1000) NOT NULL,  -- 值的 code 或原始字符串
  attr_type    VARCHAR(50) DEFAULT 'string', -- 'string','int','json','bool'
  created_at   TIMESTAMP DEFAULT now(),
  updated_at   TIMESTAMP DEFAULT now(),
  UNIQUE(resource_type, resource_id, attr_key)
);


-- i18n 表（增加 resource_type 以避免冲突）
CREATE TABLE gmt_i18n (
  i18n_id      BIGSERIAL PRIMARY KEY,
  tenant_id    VARCHAR(20) DEFAULT '000000'::varchar,
  resource_type VARCHAR(50) NOT NULL,   -- 'sku_attr_key', 'sku_attr_value', 'spu_name', ...
  resource_key  VARCHAR(200) NOT NULL,  -- 比如 attr_key 或 attr_value_code 或 'spu:123:title'
  lang         VARCHAR(10) NOT NULL,    -- 'zh','en','ja'
  text         VARCHAR(1000) NOT NULL,  -- 显示文本
  created_at   TIMESTAMP DEFAULT now(),
  UNIQUE(resource_type, resource_key, lang)
);

-- product_display_snapshot_lang: 商品展示快照表  每个 product(spu) 每种语言一条最新快照
CREATE TABLE IF NOT EXISTS product_display_snapshot_lang (
  snapshot_id      BIGSERIAL PRIMARY KEY,
  product_id       BIGINT NOT NULL,            -- spu_id
  lang             VARCHAR(10) NOT NULL DEFAULT 'zh',
  version BIGINT NOT NULL DEFAULT 1,
  snapshot_data    JSONB NOT NULL,             -- 最终展示 JSON（含规格/价格/图片等）
  updated_at       TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (product_id, lang)
);

-- 新建汇率表
CREATE TABLE exchange_rate(
    rate_id BIGSERIAL PRIMARY KEY,
    currency_code VARCHAR(10) NOT NULL, -- 货币代码
    base_currency VARCHAR(10) NOT NULL, -- 基准货币
    rate NUMERIC(10,6) NOT NULL, -- 汇率
    effective_date TIMESTAMP NOT NULL, -- 生效日期
    expiration_date TIMESTAMP, -- 失效日期
    UNIQUE (currency_code, base_currency, effective_date)
);

-- 新建国家/地区信息表
CREATE TABLE country_info(
    country_code CHAR(2) PRIMARY KEY, -- ISO 3166-1 alpha-2
    country_name VARCHAR(100) NOT NULL,
    currency VARCHAR(10) NOT NULL, -- 默认货币
    decimal places INT4 DEFAULT 2, -- 小数位数
    thousand separator VARCHAR(10) DEFAULT ',', -- 千位分隔符
    decimal separator VARCHAR(10) DEFAULT '.', -- 小数点分隔符
    address_format VARCHAR(200) NOT NULL -- 地址格式模板
);

七、可替代策略（混合更稳妥）

小范围动态字段使用 JSONB

对“非常少量且读多写少”的动态扩展属性，用 jsonb 存在主表（SPU/SKU）里，优点：查询简单、无行膨胀、可用 GIN 索引。缺点：跨实体共性搜索困难。

适合不需要在索引或筛选中频繁使用的字段。

核心字段列化 + 扩展表

重要且常筛选的字段继续列化（如 color、size、material、weight）——性能最好。

次要或很少用的字段放到 gmt_attributes。

为 i18n 建“资源命名规则”

例如 resource_type 使用精细枚举：spu:title, sku:desc, attr:key, attr:value，避免混淆。

即使存在折扣、费率等导致小数的场景，“分 + 整数”方案依然适用且推荐！
只需做到：
中间计算用高精度（DECIMAL）
最终结果按业务规则舍入到整数分
全系统统一单位（分）和舍入逻辑
关键金额可追溯计算过程
在数据库注释或数据字典中明确标注：“所有金额单位为分，整数存储”
在 API 文档中强调：“price: integer, unit: cent”
对账系统需支持“舍入差异 ≤ 1 分”的容错
这样既能保证精度安全，又能保持系统简洁高效。
所有业务代码禁止直接使用 Math.round() 或 (int)(x + 0.5) 等不安全方式。







create table if not exists test_bob
(
    bob_id     int8,
    tenant_id   varchar(20) default '000000'::varchar,
    bob_name   varchar(30) default ''::varchar,
    bob_category varchar(100) default null::varchar,
    order_num   int4        default 0,
    leader      int8        default null,
    phone       varchar(11) default null::varchar,
    email       varchar(50) default null::varchar,
    status      char        default '0'::bpchar,
    del_flag    char        default '0'::bpchar,
    create_bob int8,
    create_by   int8,
    create_time timestamp,
    update_by   int8,
    update_time timestamp,
    constraint "test_bob_pk" primary key (bob_id)
);

comment on table test_bob               is '鲍勃表';
comment on column test_bob.bob_id      is '鲍勃ID';
comment on column test_bob.tenant_id    is '租户编号';
comment on column test_bob.bob_name    is '鲍勃名称';
comment on column test_bob.bob_category    is '鲍勃类别编码';
comment on column test_bob.order_num    is '显示顺序';
comment on column test_bob.leader       is '负责人';
comment on column test_bob.phone        is '联系电话';
comment on column test_bob.email        is '邮箱';
comment on column test_bob.status       is '鲍勃状态（0正常 1停用）';
comment on column test_bob.del_flag     is '删除标志（0代表存在 1代表删除）';
comment on column test_bob.create_bob  is '创建鲍勃';
comment on column test_bob.create_by    is '创建者';
comment on column test_bob.create_time  is '创建时间';
comment on column test_bob.update_by    is '更新者';
comment on column test_bob.update_time  is '更新时间';


三、未来扩展性分析（按业务维度）

下面分析不同业务引入后你的结构是否支持。

1）外卖扩展

外卖核心关键字段：

配送范围

起送价

配送费

配送时间

商家地点

✔ 商品体系：适配
✔ SKU 库存：适配 daily_limit 和 infinite 模式
✔ 订单：需增加配送字段（extend_json）
✔ 活动：OK

→ 可支持

2）旅游 & 门票

门票关键：

有效期

验证方式（二维码）

一票多用

是否实名

→ 建议全部放 extend_json 中
→ SKU infinite 库存模式

→ 你的设计完全能支持

3）吃喝玩乐（服务券、代金券）

服务型商品往往：

无库存

需要预约时间

可退款规则不同

→ 你的结构完全能支持
→ 订单需要 extend_json

4）秒杀

秒杀需要：

活动库存

秒杀价格

限购

高并发库存扣减

你的 activity + activity_product 正好完美支持秒杀：

秒杀商品=一种特殊 activity

秒杀价 = activity_product.group_price

秒杀库存 = stock_quantity

限购 = limit_per_user

唯一需要加强：

秒杀库存扣减必须使用 PostgreSQL 行级锁或函数

推荐使用：

UPDATE gmt_activity_product
SET stock_quantity = stock_quantity - 1
WHERE activity_product_id = ?
AND stock_quantity > 0;
